/**
 * Helpers whose package README does not name them yet, per package, one name per line.
 *
 * `coverage.ts` excuses each name here from the README line the coverage rule asks of a helper.
 * The list only shrinks: when a README names one of these in code, the coverage test fails until
 * the name is removed from here. Adding a new export here to skip its README line is what review
 * refuses.
 *
 * Seeded with every helper no README named when the guide stopped showing helpers (#357).
 */

import type { PackageId } from "./registry.ts"

/** Names awaiting a README line, by package; alphabetical, so a removal touches one line. */
export const README_PENDING: Record<PackageId, readonly string[]> = {
  ui: [
    "activeDescendant",
    "addDays",
    "applyScrollLock",
    "avatarFace",
    "backdropClickDismisses",
    "backdropDismissesByDefault",
    "barHeightRem",
    "bindEscapeClose",
    "calendarDateInZone",
    "CANCEL_LABEL",
    "clampConfidence",
    "clampProgress",
    "classifyFiles",
    "clientWidthWithoutScrollbar",
    "comboboxKey",
    "comboboxKeyAction",
    "comboboxListboxId",
    "comboboxOptionId",
    "CONFIRM_LABEL",
    "confirmVariant",
    "copyToClipboard",
    "counterText",
    "dateRangePresets",
    "defaultGetLabel",
    "dialogHeldFocus",
    "dialogTitleId",
    "DISMISS_KEY",
    "editableText",
    "endOfMonth",
    "endOfQuarter",
    "endOfYear",
    "enhancedFormMessage",
    "escapeCloseStrategy",
    "failedAfterSrcChange",
    "filterItems",
    "fold",
    "formatBytes",
    "formatIsoDate",
    "formatProgressPercent",
    "groupLabel",
    "groupSplit",
    "hasQuestion",
    "HONEYPOT_FIELD_NAME",
    "honeypotField",
    "honeypotFilled",
    "initials",
    "isBackdropClick",
    "isDismissKey",
    "isSameDay",
    "isValidDateRange",
    "labelOr",
    "labelTarget",
    "leavesCombobox",
    "lineBoxRem",
    "listboxContent",
    "matchesAccept",
    "matchesQuery",
    "naming",
    "nextComboboxState",
    "nextMenuIndex",
    "normalizeCiStatus",
    "openingState",
    "pageRange",
    "parseIsoDate",
    "platformCloseHandler",
    "progressWidthPercent",
    "requestGeolocation",
    "resolveLabels",
    "resolveMoneyInputEdit",
    "scrollLockPadding",
    "selectableIndex",
    "shiftMonth",
    "SKELETON_METRICS",
    "skeletonCount",
    "skeletonStatusRole",
    "startOfMonth",
    "startOfQuarter",
    "startOfYear",
    "supportsClosedBy",
    "tableGeometry",
    "textGeometry",
    "thumbnailKey",
    "timeRangePresets",
    "typingState",
    "wrapIndex",
  ],
  charts: [
    "barPercent",
    "createInViewObserver",
    "DEFAULT_AXIS_COLOR",
    "DEFAULT_CHART_PALETTE",
    "DEFAULT_GRID_COLOR",
    "DEFAULT_SURFACE_COLOR",
    "DEFAULT_TEXT_COLOR",
    "DEFAULT_TRACK_COLOR",
    "defaultTooltipFormat",
    "donutGeometry",
    "seriesColor",
    "timeSeriesPointSchema",
  ],
  map: [],
  system: [
    "collectSequence",
    "DEFAULT_UPDATE_MESSAGE",
    "describeCalendarDay",
    "isCurrentLink",
    "reloadOnControllerChange",
    "seoHeadJsonLd",
    "serviceWorkerContainer",
    "skipWaiting",
    "TAB_BAR_SLOTS",
    "watchForUpdate",
    "zoomableAlt",
  ],
  crud: [
    "associationActions",
    "commitNumber",
    "CONFLICT",
    "editorState",
    "fieldText",
    "isRestorable",
    "listRows",
    "rowsForStatus",
    "submitEditor",
    "toggleArchiveState",
  ],
  theme: [],
  signals: [],
  cn: [],
}
