/**
 * `@spy4x/preact-theme` — TypeScript entry point.
 *
 * The design system itself is two plain CSS files, `tokens.css` and `preset.css` (see
 * `README.md`), and JSR refuses a CSS file as a package export: "Expected a JavaScript or
 * TypeScript module, but identified a Css module." A JSR-installed copy of this package cannot be
 * read by a `file:` path either — `import.meta.url` inside a module served from the registry is
 * the registry's own `https:` address, not a location on disk, so there is no path a consumer
 * could resolve a sibling file against even if `exports` allowed pointing at one.
 *
 * The stylesheets are exported as text instead. `TOKENS_CSS`, `PRESET_CSS` and `INK_CSS` are
 * generated from `tokens.css`/`preset.css`/`ink.css` by `generate.ts`
 * (`deno task --cwd theme generate`), so a shipped constant and the file it came from cannot drift
 * apart by hand — `css-text.test.ts` fails if they ever do. `README.md` → "Install" has the
 * Tailwind 4 recipe that turns these strings into the compiled design system; "Theming" → "Ink"
 * has the one extra import that adds the optional ink theme.
 *
 * `INK_CSS` is an additional, opt-in palette (#257): a second selector, `[data-theme="ink"]`,
 * applied together with `.dark` — the default Eirene palette in `TOKENS_CSS`/`PRESET_CSS` is
 * unaffected by importing it.
 *
 * `COMPONENT_CLASSES` is every Tailwind class the published components can render, generated by
 * `generate-classes.ts` from the packages' sources (#323). An app passes it to
 * `@source inline("…")`, so its Tailwind build emits those classes without scanning the library's
 * files — which a Deno app cannot do reliably, because JSR packages live in Deno's cache.
 */

export { COMPONENT_CLASSES } from "./component-classes.ts"
export { INK_CSS } from "./ink-css.ts"
export { PRESET_CSS } from "./preset-css.ts"
export { TOKENS_CSS } from "./tokens-css.ts"
