/**
 * Proves `COMPONENT_CLASSES` — what an app hands to `@source inline("…")` — is current, and that
 * Tailwind reads every class in it.
 *
 * The list is generated by `generate-classes.ts` and committed. Nothing else fails when a component
 * gains a class and nobody regenerates: `deno task check` and every dry run stay green, and the app
 * ships that component unstyled. The first test here is that guard.
 */

import { expect } from "@std/expect"
import { describe, it } from "@std/testing/bdd"
import { compile } from "tailwindcss"
import { fileURLToPath } from "node:url"
import { COMPONENT_CLASSES } from "./+index.ts"
import { componentClasses, keepClasses } from "./generate-classes.ts"
import { stylesheetLoader } from "./integration/load-stylesheet.ts"

const THEME_DIRECTORY = fileURLToPath(new URL("./", import.meta.url))

/** The stylesheets an app compiles against, as `theme/README.md` → "Install" writes them. */
const APP_ENTRY = `@import "tailwindcss";\n@import "./tokens.css";\n@import "./preset.css";\n`

/** Compile `css` the way an app's build does and return the stylesheet for `candidates`. */
async function build(css: string, candidates: string[]): Promise<string> {
  const compiler = await compile(css, {
    base: THEME_DIRECTORY,
    loadStylesheet: stylesheetLoader("4.1.12"),
  })
  return compiler.build(candidates)
}

describe("COMPONENT_CLASSES", () => {
  it("lists exactly the classes the published packages' sources render", async () => {
    const committed = COMPONENT_CLASSES.split(" ")
    const current = await componentClasses()
    // Named differences first, so a failure says which class to regenerate for.
    expect({
      missing: current.filter((name) => !committed.includes(name)),
      stale: committed.filter((name) => !current.includes(name)),
    }).toEqual({ missing: [], stale: [] })
    expect(COMPONENT_CLASSES).toBe(current.join(" "))
  })

  it("makes @source inline emit every listed class, as a scan of the same classes would", async () => {
    const inline = await build(`${APP_ENTRY}@source inline("${COMPONENT_CLASSES}");\n`, [])
    const scanned = await build(APP_ENTRY, COMPONENT_CLASSES.split(" "))
    expect(inline).toBe(scanned)
    expect(inline).toContain(".lg\\:w-64")
    expect(inline).toContain(".sr-only")
    expect(inline).toContain(".focus\\:not-sr-only")
  })
})

describe("keepClasses", () => {
  it("keeps the words that compile to CSS, including the preset's utilities, and drops the rest", async () => {
    expect(await keepClasses(["sr-only", "useState", "btn", "sr-only", "the"])).toEqual([
      "btn",
      "sr-only",
    ])
  })

  it("refuses a class that cannot be written inside @source inline", async () => {
    await expect(keepClasses(["sr-only", `content-["x"]`])).rejects.toThrow(
      `cannot be written inside @source inline`,
    )
  })
})
