/**
 * Proves `COMPONENT_CLASSES` — what an app hands to `@source inline("…")` — is current, and that
 * Tailwind reads every class in it.
 *
 * The list is generated by `generate-classes.ts` and committed. Nothing else fails when a component
 * gains a class and nobody regenerates: `deno task check` and every dry run stay green, and the app
 * ships that component unstyled. The first test here is that guard.
 */

import { expect } from "@std/expect"
import { describe, it } from "@std/testing/bdd"
import { Scanner } from "@tailwindcss/oxide"
import { compile } from "tailwindcss"
import { fileURLToPath } from "node:url"
import { COMPONENT_CLASSES } from "./+index.ts"
import { componentClasses, keepClasses } from "./generate-classes.ts"
import { stylesheetLoader } from "./integration/load-stylesheet.ts"

const THEME_DIRECTORY = fileURLToPath(new URL("./", import.meta.url))

/** The stylesheets an app compiles against, as `theme/README.md` → "Install" writes them. */
const APP_ENTRY = `@import "tailwindcss";\n@import "./tokens.css";\n@import "./preset.css";\n`

/** Compile `css` the way an app's build does and return the stylesheet for `candidates`. */
async function build(css: string, candidates: string[]): Promise<string> {
  const compiler = await compile(css, {
    base: THEME_DIRECTORY,
    loadStylesheet: stylesheetLoader("4.1.12"),
  })
  return compiler.build(candidates)
}

describe("COMPONENT_CLASSES", () => {
  it("lists exactly the classes the published packages' sources render", async () => {
    const committed = COMPONENT_CLASSES.split(" ")
    const current = await componentClasses()
    // Named differences first, so a failure says which class to regenerate for.
    expect({
      missing: current.filter((name) => !committed.includes(name)),
      stale: committed.filter((name) => !current.includes(name)),
    }).toEqual({ missing: [], stale: [] })
    expect(COMPONENT_CLASSES).toBe(current.join(" "))
  })

  it("makes @source inline emit every listed class, as a scan of the same classes would", async () => {
    const inline = await build(`${APP_ENTRY}@source inline("${COMPONENT_CLASSES}");\n`, [])
    const scanned = await build(APP_ENTRY, COMPONENT_CLASSES.split(" "))
    expect(inline).toBe(scanned)
    expect(inline).toContain(".lg\\:w-64")
    expect(inline).toContain(".sr-only")
    expect(inline).toContain(".focus\\:not-sr-only")
  })
})

describe("colour classes in ui/", () => {
  it("compile to CSS for every token class the ui sources write", async () => {
    const utilities = new Set<string>()
    const preset = await Deno.readTextFile(new URL("./preset.css", import.meta.url))
    for (const match of preset.matchAll(/^@utility ([a-z-]+) \{/gm)) utilities.add(match[1])
    const tokens = new Set<string>()
    const tokenCss = await Deno.readTextFile(new URL("./tokens.css", import.meta.url))
    for (const match of tokenCss.matchAll(/--color-([a-z0-9-]+):/g)) tokens.add(match[1])

    const written = new Set<string>()
    const directory = new URL("../ui/", import.meta.url)
    for await (const entry of Deno.readDir(directory)) {
      if (!entry.name.endsWith(".tsx") || entry.name.endsWith(".test.tsx")) continue
      const source = await Deno.readTextFile(new URL(entry.name, directory))
      for (
        const match of source.matchAll(
          /(?<![\w-])((?:[a-z0-9-]+:)*)(bg|text|border|ring|divide|decoration)-([a-z]+(?:-[a-z]+)*)(?![\w(-])/g,
        )
      ) {
        const [word, , prefix, value] = match
        if (utilities.has(`${prefix}-${value}`) || tokens.has(value)) written.add(word)
      }
    }
    expect(written.size).toBeGreaterThan(50)

    const css = await build(APP_ENTRY, [...written])
    const silent = [...written].filter((word) => !css.includes(`.${word.replaceAll(":", "\\:")}`))
    // A class that generates nothing is dropped from COMPONENT_CLASSES without a word, and the
    // component then draws no colour at all (`ring-scrim-foreground` did).
    expect(silent).toEqual([])
  })
})

/**
 * A page an app writes, in its own words: every word the preset once had a class for appears in
 * its text, its markup and its code, as it would in a real form, dashboard or article (#469).
 */
const APP_PAGE = `
<h2>Billing</h2>
<p>Type your address into an input field, select a plan, then check the card for a link to the bar
chart. Each label sits beside its checkbox or radio; a textarea takes the notes. The kpi row shows
one num per scrollbar step, from h1 down to h5.</p>
<input type="checkbox" name="link" /> <label for="card">card</label>
<script>const input = select(card.link, bar, num, kpi)</script>
`

/** The class names Tailwind's own scanner extracts from `content`, as an app's build sees them. */
function scannedWords(content: string): string[] {
  return new Scanner({}).getCandidatesWithPositions({ content, extension: "html" }).map((
    { candidate },
  ) => candidate)
}

describe("an app's own words", () => {
  it("emit none of the preset's rules", async () => {
    const words = scannedWords(APP_PAGE)
    // The scanner does read these words, so the check below is about the preset, not the scanner.
    const preset = ["input", "select", "card", "link", "label", "checkbox", "bar", "num", "h1"]
    expect(preset.filter((word) => !words.includes(word))).toEqual([])
    expect(await build(APP_ENTRY, words)).toBe(await build(APP_ENTRY, []))
  })

  it("emit the prefixed rule once the app names it", async () => {
    expect(await build(APP_ENTRY, scannedWords(`<div class="pc-card">x</div>`))).toContain(
      ".pc-card",
    )
  })
})

describe("keepClasses", () => {
  it("keeps the words that compile to CSS, including the preset's utilities, and drops the rest", async () => {
    expect(await keepClasses(["sr-only", "useState", "btn", "sr-only", "the"])).toEqual([
      "btn",
      "sr-only",
    ])
  })

  it("refuses a class that cannot be written inside @source inline", async () => {
    await expect(keepClasses(["sr-only", `content-["x"]`])).rejects.toThrow(
      `cannot be written inside @source inline`,
    )
  })
})
