/**
 * Proves `TOKENS_CSS`/`PRESET_CSS` — what a consumer actually gets — match the CSS files that are
 * this design system's source of truth.
 *
 * The two constants are generated by `generate.ts` and never hand-edited, but nothing stops a
 * contributor from editing `tokens.css`/`preset.css` and forgetting to re-run it, and nothing
 * mechanical catches that except this comparison: `deno task check` and every package's dry run
 * stay green regardless of what the generated text says (see the pull request body for the
 * mutation that proved it).
 */

import { expect } from "@std/expect"
import { describe, it } from "@std/testing/bdd"
import { INK_CSS, PRESET_CSS, TOKENS_CSS } from "./+index.ts"

describe("the generated CSS text constants", () => {
  it("TOKENS_CSS matches tokens.css byte for byte", async () => {
    const source = await Deno.readTextFile(new URL("./tokens.css", import.meta.url))
    expect(TOKENS_CSS).toBe(source)
  })

  it("PRESET_CSS matches preset.css byte for byte", async () => {
    const source = await Deno.readTextFile(new URL("./preset.css", import.meta.url))
    expect(PRESET_CSS).toBe(source)
  })

  it("INK_CSS matches ink.css byte for byte", async () => {
    const source = await Deno.readTextFile(new URL("./ink.css", import.meta.url))
    expect(INK_CSS).toBe(source)
  })
})

/**
 * Every default-palette declaration `tokens.css` carried before #257 added `INK_CSS` and the two
 * font tokens, copied here verbatim rather than re-derived, so a change to any of them fails this
 * test by name instead of passing because the assertion moved with the file. This is the "every
 * existing token resolves to the same value" half of #257's done-when: ink is additive, and the
 * default (Eirene) palette renders exactly as it did before this change.
 */
const UNCHANGED_DEFAULT_TOKEN_DECLARATIONS = [
  `--color-primary: oklch(0.38 0.17 293); /* purple-900 */`,
  `--color-primary-foreground: oklch(0.977 0.014 308.299); /* purple-50 */`,
  `--color-primary-muted: oklch(0.558 0.288 302.321); /* purple-600 */`,
  `--color-surface: oklch(1 0 0); /* white */`,
  `--color-canvas: oklch(0.985 0.002 247.839); /* gray-50 */`,
  `--color-border-subtle: oklch(0.928 0.006 264.531); /* gray-200 */`,
  `--color-border-control: oklch(0.872 0.01 258.338); /* gray-300 */`,
  `--color-foreground: oklch(0.13 0.028 261.692); /* gray-950 */`,
  `--color-muted-foreground: oklch(0.551 0.027 264.364); /* gray-500 */`,
  `--color-placeholder: oklch(0.551 0.027 264.364); /* gray-500 */`,
  `--color-danger: oklch(0.577 0.245 27.325); /* red-600 */`,
  `--color-danger-foreground: oklch(0.971 0.013 17.38); /* red-50 */`,
  `--color-warning: oklch(0.646 0.222 41.116); /* orange-600 */`,
  `--color-warning-foreground: oklch(0.98 0.016 73.684); /* orange-50 */`,
  `--color-success: oklch(0.527 0.154 150.069); /* green-700 */`,
  `--color-success-foreground: oklch(0.982 0.018 155.826); /* green-50 */`,
  `--radius-primary: 0.5rem; /* rounded-lg */`,
  `--radius-control: 0.375rem; /* rounded-md */`,
  `--font-sans: "Poppins", ui-sans-serif, system-ui, sans-serif;`,
  `--color-primary: oklch(0.21 0.006 285.885); /* near-black chrome, not purple */`,
  `--color-primary-muted: oklch(0.714 0.203 305.504); /* purple-400 */`,
  `--color-surface: oklch(0.278 0.033 256.848); /* gray-800 */`,
  `--color-canvas: oklch(0.21 0.034 264.665); /* gray-900 */`,
  `--color-border-subtle: oklch(0.373 0.034 259.733); /* gray-700 */`,
  `--color-border-control: oklch(0.446 0.03 256.802); /* gray-600 */`,
  `--color-foreground: oklch(0.985 0.002 247.839); /* gray-50 */`,
  `--color-muted-foreground: oklch(0.707 0.022 261.325); /* gray-400 */`,
  `--color-placeholder: oklch(0.707 0.022 261.325); /* gray-400 */`,
  `--color-danger: oklch(0.637 0.237 25.331); /* red-500 */`,
]

describe("the default token set, after #257", () => {
  it("still declares every pre-existing token at its pre-existing value", () => {
    for (const declaration of UNCHANGED_DEFAULT_TOKEN_DECLARATIONS) {
      expect(TOKENS_CSS, `missing or changed: ${declaration}`).toContain(declaration)
    }
  })

  it("adds --font-serif and --font-mono as system stacks, no font files", () => {
    expect(TOKENS_CSS).toContain(`--font-serif: ui-serif,`)
    expect(TOKENS_CSS).toContain(`--font-mono: ui-monospace,`)
    expect(TOKENS_CSS).not.toMatch(/\.(woff2?|ttf|otf)/)
  })
})
