/**
 * Proves `TOKENS_CSS`/`PRESET_CSS` — what a consumer actually gets — match the CSS files that are
 * this design system's source of truth.
 *
 * The two constants are generated by `generate.ts` and never hand-edited, but nothing stops a
 * contributor from editing `tokens.css`/`preset.css` and forgetting to re-run it, and nothing
 * mechanical catches that except this comparison: `deno task check` and every package's dry run
 * stay green regardless of what the generated text says (see the pull request body for the
 * mutation that proved it).
 */

import { expect } from "@std/expect"
import { describe, it } from "@std/testing/bdd"
import { PRESET_CSS, TOKENS_CSS } from "./+index.ts"

describe("the generated CSS text constants", () => {
  it("TOKENS_CSS matches tokens.css byte for byte", async () => {
    const source = await Deno.readTextFile(new URL("./tokens.css", import.meta.url))
    expect(TOKENS_CSS).toBe(source)
  })

  it("PRESET_CSS matches preset.css byte for byte", async () => {
    const source = await Deno.readTextFile(new URL("./preset.css", import.meta.url))
    expect(PRESET_CSS).toBe(source)
  })
})
