/**
 * Proves `TOKENS_CSS`/`PRESET_CSS` — what a consumer actually gets — match the CSS files that are
 * this design system's source of truth.
 *
 * The two constants are generated by `generate.ts` and never hand-edited, but nothing stops a
 * contributor from editing `tokens.css`/`preset.css` and forgetting to re-run it, and nothing
 * mechanical catches that except this comparison: `deno task check` and every package's dry run
 * stay green regardless of what the generated text says (see the pull request body for the
 * mutation that proved it).
 */

import { expect } from "@std/expect"
import { describe, it } from "@std/testing/bdd"
import { INK_CSS, PRESET_CSS, TOKENS_CSS } from "./+index.ts"

describe("the generated CSS text constants", () => {
  it("TOKENS_CSS matches tokens.css byte for byte", async () => {
    const source = await Deno.readTextFile(new URL("./tokens.css", import.meta.url))
    expect(TOKENS_CSS).toBe(source)
  })

  it("PRESET_CSS matches preset.css byte for byte", async () => {
    const source = await Deno.readTextFile(new URL("./preset.css", import.meta.url))
    expect(PRESET_CSS).toBe(source)
  })

  it("INK_CSS matches ink.css byte for byte", async () => {
    const source = await Deno.readTextFile(new URL("./ink.css", import.meta.url))
    expect(INK_CSS).toBe(source)
  })
})

/** The opening of `tokens.css`'s one `@layer` rule, as a regular-expression fragment. */
const TOKENS_LAYER_OPEN = "@layer theme\\.preact-tokens\\s*\\{"

/**
 * Parses a top-level `selector { ... }` block's declarations into a property → value map, so a
 * comparison can catch an appended or reordered declaration that a `toContain` check on a fixed
 * string cannot: `toContain` only proves the listed strings are somewhere in the file, not that
 * nothing else was added alongside them (a duplicate `--color-primary` appended after the real one
 * still contains the original string). Comments are stripped before parsing, and only the requested
 * selector's own braces are read — `tokens.css` has exactly one `:root` and one `.dark` block, both
 * flat, so a non-greedy match up to the first closing brace is exact. Since #470 both open its
 * `@layer` rule's body, so a block counts when it follows that rule's opening brace or a closing
 * brace; the `:root` inside `@supports` follows neither.
 */
function parseBlock(css: string, selector: string): Record<string, string> {
  const withoutComments = css.replace(/\/\*[\s\S]*?\*\//g, "")
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
  const blocks =
    withoutComments.match(new RegExp(`(^|\\}|${TOKENS_LAYER_OPEN})\\s*${escaped}\\s*\\{`, "g")) ??
      []
  if (blocks.length !== 1) throw new Error(`expected one ${selector} block, found ${blocks.length}`)
  const match = withoutComments.match(new RegExp(`${escaped}\\s*\\{([\\s\\S]*?)\\}`))
  if (!match) throw new Error(`no ${selector} block found`)
  const declarations: Record<string, string> = {}
  for (const line of match[1].split(";")) {
    const trimmed = line.trim()
    if (!trimmed) continue
    const colon = trimmed.indexOf(":")
    if (colon === -1) continue
    declarations[trimmed.slice(0, colon).trim()] = trimmed.slice(colon + 1).trim()
  }
  return declarations
}

/**
 * Every default-palette token `tokens.css` declares, copied here as a property → value map rather
 * than re-derived, so a changed, removed or appended declaration in either block fails this test
 * by name. #257 introduced it to prove that ink is additive; a later change to the default palette
 * updates the map on purpose, with a comment naming its issue.
 */
const EXPECTED_ROOT_TOKENS: Record<string, string> = {
  // #380 moved --color-primary from an approximation 12 degrees of hue off to the purple-900 its
  // comment always named, so the components that now read it keep drawing Tailwind's purple-900,
  // and added the accent the components read: --color-primary, and step 900 of its scale.
  "--color-primary": "oklch(0.381 0.176 304.987)",
  "--color-primary-foreground": "oklch(0.977 0.014 308.299)",
  "--color-primary-muted": "oklch(0.558 0.288 302.321)",
  "--color-accent": "var(--color-primary)",
  "--color-accent-900": "var(--color-accent)",
  "--color-surface": "oklch(1 0 0)",
  // #358 moved these two: the canvas a step darker so a card stands off it, and muted text a step
  // darker so it keeps AA contrast on that canvas.
  "--color-canvas": "oklch(0.967 0.003 264.542)",
  "--color-border-subtle": "oklch(0.928 0.006 264.531)",
  "--color-border-control": "oklch(0.872 0.01 258.338)",
  "--color-foreground": "oklch(0.13 0.028 261.692)",
  "--color-muted-foreground": "oklch(0.446 0.03 256.802)",
  "--color-placeholder": "oklch(0.551 0.027 264.364)",
  // #463: the light status text a step or two darker, so it reads at 4.5:1 on the surface and the
  // canvas; the fills below keep the steps the text tokens used to have.
  "--color-danger": "oklch(0.505 0.213 27.518)",
  "--color-danger-foreground": "oklch(0.971 0.013 17.38)",
  "--color-warning": "oklch(0.553 0.195 38.402)",
  // #431: a dark label, because orange-50 read 3.37:1 on the orange-600 fill.
  "--color-warning-foreground": "oklch(0.13 0.028 261.692)",
  "--color-success": "oklch(0.448 0.119 151.328)",
  "--color-success-foreground": "oklch(0.982 0.018 155.826)",
  // #429: the warning and success fills; #463 gave them their own values when the text darkened.
  "--color-warning-fill": "oklch(0.646 0.222 41.116)",
  "--color-success-fill": "oklch(0.527 0.154 150.069)",
  "--radius-primary": "0.5rem",
  "--radius-control": "0.375rem",
  // #417 added the tokens below. Most are read by nothing yet (selection, focus, hover, track,
  // scrim, the soft tints, the card radius, the shadows). The Button's primary and danger variants
  // read the accent-foreground and danger-fill ones, and their defaults draw the colours the
  // Button drew before (white on red-600, its hover red-700, a white label on the purple accent).
  "--color-accent-foreground": `oklch(1 0 0)`, // the fallback where the luminance probe cannot run
  "--color-selected": `var(--color-accent-900)`,
  "--color-selected-foreground": `var(--color-accent-foreground)`,
  "--color-selected-soft": `var(--color-accent-50)`,
  "--color-selected-text": `var(--color-accent-900)`,
  "--color-selected-hover": `var(--color-accent-800)`,
  "--color-selected-soft-hover": `var(--color-accent-100)`,
  "--color-focus-offset": `var(--color-canvas)`,
  "--color-ring": `var(--color-accent-900)`,
  "--color-hover": `oklch(0.967 0.003 264.542)`,
  "--color-track": `oklch(0.928 0.006 264.531)`,
  "--color-scrim": `oklch(0 0 0 / 0.5)`,
  "--color-scrim-strong": `oklch(0 0 0 / 0.9)`,
  "--color-scrim-foreground": `oklch(1 0 0)`,
  "--color-border-strong": `oklch(0.707 0.022 261.325)`,
  "--color-danger-fill": `oklch(0.577 0.245 27.325)`,
  "--color-danger-fill-hover": `oklch(0.505 0.213 27.518)`,
  "--color-danger-fill-foreground": `oklch(1 0 0)`,
  "--color-danger-soft": `oklch(0.971 0.013 17.38)`,
  "--color-info": `oklch(0.546 0.245 262.881)`,
  "--color-info-foreground": `oklch(0.97 0.014 254.604)`,
  "--color-info-soft": `oklch(0.97 0.014 254.604)`,
  "--color-warning-soft": `oklch(0.98 0.016 73.684)`,
  "--color-success-soft": `oklch(0.982 0.018 155.826)`,
  "--radius-card": `0.75rem`,
  "--shadow-raised": `0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)`,
  "--shadow-popover": `0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)`,
}

const EXPECTED_DARK_TOKENS: Record<string, string> = {
  "--color-primary": "oklch(0.21 0.006 285.885)",
  // #380: the components' accent stays purple-900 where --color-primary is near-black chrome.
  "--color-accent": "oklch(0.381 0.176 304.987)",
  "--color-primary-foreground": "oklch(0.977 0.014 308.299)",
  "--color-primary-muted": "oklch(0.714 0.203 305.504)",
  "--color-surface": "oklch(0.278 0.033 256.848)",
  "--color-canvas": "oklch(0.21 0.034 264.665)",
  "--color-border-subtle": "oklch(0.373 0.034 259.733)",
  "--color-border-control": "oklch(0.446 0.03 256.802)",
  "--color-foreground": "oklch(0.985 0.002 247.839)",
  "--color-muted-foreground": "oklch(0.707 0.022 261.325)",
  "--color-placeholder": "oklch(0.707 0.022 261.325)",
  // #429: status text reads at 4.5:1 on the dark surface and canvas; the fills keep their steps.
  "--color-danger": "oklch(0.704 0.191 22.216)",
  "--color-warning": "oklch(0.75 0.183 55.934)",
  "--color-success": "oklch(0.792 0.209 151.711)",
  "--color-warning-fill": "oklch(0.646 0.222 41.116)",
  "--color-success-fill": "oklch(0.527 0.154 150.069)",
  "--color-hover": `oklch(0.373 0.034 259.733)`,
  "--color-track": `oklch(0.446 0.03 256.802)`,
  "--color-border-strong": `oklch(0.551 0.027 264.364)`,
  // #434: the selected fill and the focus ring stand off the dark page.
  "--color-selected": `var(--color-accent-600)`,
  "--color-ring": `var(--color-accent-400)`,
  "--color-selected-soft": `color-mix(in oklab, var(--color-accent-900) 30%, transparent)`,
  "--color-selected-text": `var(--color-accent-400)`,
  "--color-selected-soft-hover": `color-mix(in oklab, var(--color-accent-900) 50%, transparent)`,
  "--color-danger-fill": `oklch(0.505 0.213 27.518)`,
  "--color-danger-fill-hover": `oklch(0.577 0.245 27.325)`,
  "--color-danger-soft": `color-mix(in oklab, oklch(0.505 0.213 27.518) 30%, transparent)`,
  "--color-info-soft": `color-mix(in oklab, oklch(0.546 0.245 262.881) 25%, transparent)`,
  "--color-warning-soft": `color-mix(in oklab, oklch(0.553 0.195 38.402) 30%, transparent)`,
  "--color-success-soft": `color-mix(in oklab, oklch(0.448 0.119 151.328) 30%, transparent)`,
  "--color-info": `oklch(0.707 0.165 254.624)`,
  "--color-info-foreground": `oklch(0.282 0.091 267.935)`,
}

describe("the default token set, after #257", () => {
  it("declares exactly the expected tokens at their expected values", () => {
    expect(parseBlock(TOKENS_CSS, ":root")).toEqual(EXPECTED_ROOT_TOKENS)
    expect(parseBlock(TOKENS_CSS, ".dark")).toEqual(EXPECTED_DARK_TOKENS)
  })

  it("does not redeclare a font token Tailwind's own theme declares", () => {
    const root = parseBlock(TOKENS_CSS, ":root")
    expect(root).not.toHaveProperty("--font-sans")
    expect(root).not.toHaveProperty("--font-serif")
    expect(root).not.toHaveProperty("--font-mono")
    expect(TOKENS_CSS).not.toMatch(/\.(woff2?|ttf|otf)/)
  })
})

describe("preset.css fallbacks, after #463", () => {
  it("fall back to the light value tokens.css gives each status text token", () => {
    const root = parseBlock(TOKENS_CSS, ":root")
    const fallbacks = [
      ...PRESET_CSS.matchAll(/var\((--color-(?:danger|warning|success)),\s*([^()]*\([^()]*\))\)/g),
    ]
    const mismatched = fallbacks
      .filter(([, token, fallback]) => fallback !== root[token])
      .map(([usage, token]) => `${usage} (tokens.css: ${root[token]})`)
    expect(fallbacks.length).toBe(14)
    expect(mismatched).toEqual([])
  })
})
