/**
 * Regenerates `tokens-css.ts` and `preset-css.ts` from `tokens.css` and `preset.css`.
 *
 * JSR refuses a CSS file as a package export, and a JSR-installed module cannot read a sibling
 * file by a `file:` path either — `import.meta.url` inside a module served from the registry is
 * the registry's own `https:` address, not a location on disk. The only way to ship the
 * stylesheets' text so every consumer gets it with no network call and no read permission is to
 * bake it into a `.ts` module as a string literal, which is what this script does.
 *
 * Run it after editing either CSS file:
 *
 * ```bash
 * deno task --cwd theme generate
 * ```
 *
 * `css-text.test.ts` is what actually stops the two from drifting apart — it fails when a
 * generated constant and its source file disagree — this script is the fix for that failure, not
 * the guard against it.
 */

/** Read one CSS file and write its text as a generated `.ts` module. */
async function generate(cssFile: string, tsFile: string, exportName: string): Promise<void> {
  const css = await Deno.readTextFile(new URL(cssFile, import.meta.url))
  const body = `// AUTO-GENERATED by generate.ts from ${cssFile} — do not edit by hand.
// Run \`deno task --cwd theme generate\` after editing ${cssFile}; see css-text.test.ts.

/** ${cssFile}'s exact contents. Generated — see this file's own header. */
export const ${exportName}: string = ${JSON.stringify(css)}
`
  await Deno.writeTextFile(new URL(tsFile, import.meta.url), body)
}

if (import.meta.main) {
  await generate("./tokens.css", "./tokens-css.ts", "TOKENS_CSS")
  await generate("./preset.css", "./preset-css.ts", "PRESET_CSS")
  await generate("./ink.css", "./ink-css.ts", "INK_CSS")
  console.log("generated tokens-css.ts, preset-css.ts and ink-css.ts")
}
